# Ultralytics YOLO 🚀, GPL-3.0 license
# Publish pip package to PyPI https://pypi.org/project/ultralytics/ and Docs to https://docs.ultralytics.com

name: Publish to PyPI and Deploy Docs

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      docs:
        type: boolean
        description: Deploy Docs

jobs:
  publish:
    if: github.repository == 'ultralytics/utest' && github.actor == 'glenn-jocher'
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel build twine
          pip install -e '.[dev]' --extra-index-url https://download.pytorch.org/whl/cpu
      - name: Deploy Docs
        continue-on-error: true
        if: github.event_name == 'push' || github.event.inputs.docs == 'true'
        #env:
        #  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          #git config --global user.email "glenn.jocher@ultralytics.com"
          #git config --global user.name "Glenn Jocher"

          mkdocs gh-deploy --force || true

          #git checkout gh-pages
          #git status
          #git push https://github.com/ultralytics/docs gh-pages --force
